version: '3'
services:

  jobmanager:
    image: flink:1.11.3
    ports:
      - "8081:8081"
    command: jobmanager
    volumes:
      - ./config/flink-conf.yaml:/opt/flink/conf/flink-conf.yaml:ro
      - ./config/flink-metrics-prometheus-1.11.3.jar:/opt/flink/lib/flink-metrics-prometheus-1.11.3.jar
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    networks:
      - monitoring

  taskmanager:
    image: flink:1.11.3
    #ports:
    #  - 9251:9999
    depends_on:
      - jobmanager
    command: taskmanager
    volumes:
      - ./config/flink-conf.yaml:/opt/flink/conf/flink-conf.yaml:ro
      - ./config/flink-metrics-prometheus-1.11.3.jar:/opt/flink/lib/flink-metrics-prometheus-1.11.3.jar
    #scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    networks:
      - monitoring
  
  prometheus:
    image: prom/prometheus:latest
    user: root
    container_name: prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped
    ports:
      - '9090:9090'
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter
    ports:
      - '9110:9100' #host port: container port
    networks:
      - monitoring

  cadvisor:
    image: google/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - '8080:8080'
    networks:
      - monitoring

  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    #volumes:
    #  - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - monitoring


networks:
  monitoring:
    driver: bridge