version: '3'
services:

  jobmanager:
    #image: flink:1.11.3
    image: digitaljazz/flink-1.11.3-armv7:latest
    ports:
      - "8081:8081"
    #command: jobmanager
    command: jobmanager.sh start-foreground jobmanager
    volumes:
      - ./config/flink-conf.yaml:/flink/conf/flink-conf.yaml:ro
      - ./config/flink-metrics-prometheus-1.11.3.jar:/flink/lib/flink-metrics-prometheus-1.11.3.jar
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager

  taskmanager:
    #image: flink:1.11.3
    image: digitaljazz/flink-1.11.3-armv7:latest
    depends_on:
      - jobmanager
    #command: taskmanager
    command: taskmanager.sh start-foreground -Djobmanager.rpc.address=jobmanager
    volumes:
      - ./config/flink-conf.yaml:/flink/conf/flink-conf.yaml:ro
      - ./config/flink-metrics-prometheus-1.11.3.jar:/flink/lib/flink-metrics-prometheus-1.11.3.jar
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
  
  prometheus:
    image: prom/prometheus:latest
    user: root
    container_name: prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: unless-stopped
    ports:
      - '9090:9090'

  node-exporter:
    image: prom/node-exporter
    ports:
      - '9100:9100'

  cadvisor:
    #image: google/cadvisor:latest
    image: budry/cadvisor-arm
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - '8080:8080'

  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    expose:
      - "1883"
      - "9001"
    ports:
      - "1883:1883"
      - "9001:9001"
    #volumes:
    #  - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
